### ISSUE TITLE
How to set the value of  MINUSGRADIENT in parameters.py

### ISSUE THREAD

**Issue by ZongfaWang** [adjtomo/seisflows#108]
I download the 2D checkers model from the new website https://drive.google.com/open?id=1ow3LTYEvNn55yGeIV56sqaW-wXC0MtYW, but when i run this model, there is a KeyError: 'MINUSGRADIENT' in the inversion process. I check the parameters.py file and find there isn't the parameter MINUSGRADIENT. So i want to know what is the meaning of this parameter and how to choose its value .
thanks!!!

**Comment by Jncheer** [comment]
I encountered the same problem, have you solved it?

**Comment by niyiyu2316** [comment]
In the file seisflows/workflow/inversion.py, **PAR.MINUSGRADIENT** works like this:

>          if PAR.MINUSGRADIENT:
>             optimize.save(dst, -solver.merge(parts))
>         else:
>             optimize.save(dst, solver.merge(parts))

Thus, add **MINUSGRADIENT** whatever you like in **parameters.py** such that it has the form of True or False may work.

For the latest version of SPECFEM 2D (7.0), I may try to add:

> MINUSGRADIENT=0
