### ISSUE TITLE
setup.py not working

### ISSUE THREAD

**Issue by mpbl** [adjtomo/seisflows#13]
`python setup.py install` 
works fine in a conda virtual environment set up with:
`conda create -n sf_env python=2.7 setuptools matplotlib numpy scipy`

However it a _completely_ blank environment:
`conda create -n sf_env python=2.7 setuptools`
There is some problems:
    \* mkl is not found correctly. scipy looks for numpy's mkl bindings and numpy try to get the mkl library in $MKLROOT/lib/emt64 instead of $MKLROOT/lib/intel64
    \* matplotlib complains about `__version__` not being found

**Comment by rmodrak** [comment]
Having become a little more familiar with pip, I realize now that most seisflows installations should be "editable" (``pip  -e``).  Being a research tool, it is good for users to be able to browse and modify source code.  Just an offhand comment.

**Comment by rmodrak** [comment]
Also, just to clarify, it is possible to run seisflows without ever executing setup.py, provided dependencies such as numpy and scipy are in place.   The instructions [here](http://seisflows.readthedocs.org/en/latest/instructions_remote.html) actually describe such an approach.
