### ISSUE TITLE
Multicore workstation system module

### ISSUE THREAD

**Issue by bch0w** [adjtomo/seisflows#160]
Legacy SeisFlows had the ability to run workstation problems in an embarrassingly parallel fashion in its `multicore` system sub module. 

https://github.com/adjtomo/seisflows/blob/legacy/seisflows/system/multicore.py

This feature did not make it over to modern SeisFlows, but would be very useful for those working on workstations, or for speeding up example problems.

Should be quick to overwrite the `run` function of the`Workstation` submodule and run things using multiprocessing with a few additional parameters controlling max workers.

**Comment by bch0w** [comment]
Actually this is likely already taken care of by the `Cluster` class, which submits jobs to a local system using subprocess run and concurrent futures. 

One small bug I noticed when looking over `Cluster` is that the max number of concurrent jobs (max_workers) should be `ntask_max` and not `nproc` - 1 which is what it is currently set as:

https://github.com/adjtomo/seisflows/blob/c01bc96282cd133794f0ab3cb86d3d574f103d14/seisflows/system/cluster.py#L180-L182

**Comment by bch0w** [comment]
> Actually this is likely already taken care of by the `Cluster` class, which submits jobs to a local system using subprocess run and concurrent futures.
> 
> One small bug I noticed when looking over `Cluster` is that the max number of concurrent jobs (max_workers) should be `ntask_max` and not `nproc` - 1 which is what it is currently set as:
> 
> https://github.com/adjtomo/seisflows/blob/c01bc96282cd133794f0ab3cb86d3d574f103d14/seisflows/system/cluster.py#L180-L182

This bug was fixed in 646b6c1 and I was successfully able to run an embarrassingly parallel workstation example using the Cluster system module

**Comment by Ben-J-Eppinger** [comment]
Hello, sorry to bother you on another thread.... Can you please be a bit more specific with how you set up the parameter files to run seisflows this way. My parameter file looks like the following but when I try to run in a parallel fashion, seisflows sticks for a long time without doing anything. 

system: cluster
ntask: 20
ntask_max: 20
walltime: 100:00:00
tasktime: 1000:00:00
nproc: 1
mpiexec: mpirun
log_level: DEBUG
verbose: False

**Comment by bch0w** [comment]
Hi @Ben-J-Eppinger, I think the issue is related to the fact that the parameter `nproc` in your parameter file needs to be >1, and should be equal to the number of parallel tasks you think your computer can handle at once. I usually set it equal or slightly below the total number of cores I have on the machine I'm using.

When `nproc`==1, the parallel machinery sets the total number of parallel processes to `nproc`-1=0 and that might explain why things are hanging. 

Hopefully that works, but if the issue persists please feel free to open a new issue and we can try to get it resolved!
