### ISSUE TITLE
On data in the DATABASES when running seisflows

### ISSUE THREAD

**Issue by ytian159** [adjtomo/seisflows#170]
When I was using seisflows to run multiple forward simulations (same model, different sources), there are large files generated in the DATABASES. I think those files are mainly duplicated, since all the simulation are using the same mesh? I have turn the "save_mesh_file" and "save_forward" option off, those files are still there and occupying lots of spaces. Can we have an option to avoid using so much spaces?

**Comment by bch0w** [comment]
Related to #118

**Comment by bch0w** [comment]
Closing this as complete, please re-open if that's a mistake!
