### ISSUE TITLE
Error at 'postprocess_event_kernels' stage

### ISSUE THREAD

**Issue by raulleoncz** [adjtomo/seisflows#185]
Hello @bch0w, this is a new issue related to the problem #182. 
I ran the simulation step by step and I found out that I got the problem at the step 3 of the workflow. The problem is the same as in #182. I checked the file 'adj_solver.log' and I getting this:
![Captura de pantalla 2024-01-24 203933](https://github.com/adjtomo/seisflows/assets/127082990/20dfc288-a97b-4ee7-8143-4e81fa79cd24)

In case of 'OUTPUT_FILES/output_solver.txt', there was not a file with that name.  I also see if I have the same number of traces and there was the 10 receivers that I was expecting: 
![Captura de pantalla 2024-01-24 204133](https://github.com/adjtomo/seisflows/assets/127082990/9e13f651-0be1-44af-828a-cf3ba5fb78d5)

I add you the error I got from 'combine_vp.log' just in case:
![Captura de pantalla 2024-01-24 204025](https://github.com/adjtomo/seisflows/assets/127082990/8a5e7dd5-6765-44ed-8446-5b5a9c83c9d4)

Hope you can help me. 
Thank you.

**Comment by bch0w** [comment]
Hi @raulleoncz, sorry for a slow reply here. I think I understand where this is coming from now, the kernels output by SPECFEM are in the format `proc??????_<parameter>_acoustic_kernel.bin`, whereas SeisFlows is expecting files named `proc??????_<parameter>_kernel.bin`. So the file manipulation functions are failing to catch the right kernel files and the workflow is failing.

That additional `acoustic` tag was something I was not aware of as I have not explored the 2D acoustic workflow much. Thanks for bringing this to my attention, it will likely require me to run a 2D acoustic example on my own to ensure that the file manipulation parts of the workflow are able to successfully recognize and catch these new kernel files. 

As for how you can get past this in the interim, this is a bit hacky and not guaranteed to work, but you might be able to move these kernel files to the correct location on your own. Here are some pseudo commands that you can run:

```bash
cd ~/seisflows/Tiber/scratch/solver/001/OUTPUT_FILES
mv *_kernel.bin ~/seisflows/Tiber/scratch/eval_grad/kernels/001
cd  ~/seisflows/Tiber/scratch/eval_grad/kernels/001
rename _acoustic '' *
cd ~/seisflows
seisflows resume
```

I am not 100% sure this will work as the parameter names are also different. Let me test out an acoustic example on my own and get back to you! I'll also try to work on the SU preprocessing at the same time.

**Comment by bch0w** [comment]
Hi @raulleoncz, I will close this issue and continue work on this in #202, please continue discussion in that issue. Thanks!

**Comment by dorogyn22** [comment]
Has a formal solution to the acoustic FWI naming issued been addressed?
