### ISSUE TITLE
exit gracefully when external solver fails

### ISSUE THREAD

**Issue by rmodrak** [adjtomo/seisflows#30]
It can be difficult to detect when SPECFEM or another external solver fails-- correct exit codes may not always be returned.  This can lead to misleading tracebacks-- the python code continues to run for some time longer, even though simulation results are not present or not correct.   It may be possible to fix this problem through changes to seisflows or to the external solvers themselves.

**Comment by gianmatharu** [comment]
I've ran into this on occasion. Would adding a sub process.check_call() into the run command suffice?

**Comment by rmodrak** [comment]
Yes, that might work.  For some reason I was trying to use popen and communicate before.  That was a long time ago, I may have just overlooked check_call.

If this works, I think we could simply modify the solver mpirun wrapper, adding something like the following code snippet from stackoverflow

```
try:
    subprocess.check_call(['executable'])
except subprocess.CalledProcessError:
    pass # handle errors in the called executable
except OSError:
    pass # executable not found
```

**Comment by rmodrak** [comment]
At one point, I was trying to wrap subprocess.call in unix.run for error handling.  Besides the obfuscating effect from the poorly chosen name, this function I think is unnecessary.  Unless I am forgetting something, the only case subprocess status checking is needed is for solver executables.

**Comment by rmodrak** [comment]
To clarify, we'd of course need to modify the above snippet so that executition stops after the CalledProcessError.  Something like

```
try:
    subprocess.check_call(['executable'])
except subprocess.CalledProcessError:
    raise Exception(msg.SolverError % executable_name)
except OSError:
    pass # executable not found
```

**Comment by rmodrak** [comment]
Now, in both the system and solver routines, each occurence of ``subprocess.check`` has been replaced with ``subprocess.check_call``.   A message is provided containing the failed shell command whenever a subprocess call fails.  

Minor exception: in ``system.mpi``, ``call`` is retained because ``check_call`` seems to result in unhelpful cryptic error messages.

When a call to a solver executable fails, a warning is given that any subsquent results may be invalid because expected solver output was not generated.  Unfortunately, a failed solver run still does not cause the workflow as a whole to stop--it's not clear for me how to implement this.  In some cases, for example if the cluster has some kind of built in tolerance or rerunning, this might not even be desirable in fact.
