### ISSUE TITLE
shot parallelism discussion

### ISSUE THREAD

**Issue by rmodrak** [adjtomo/seisflows#40]
On Mon, Jul 18, 2016 at 3:23 PM, Gian Matharu gian@ualberta.ca wrote:

Hi Ryan, 

So I was wondering if you've run into any issues using the MPI system class. It works fine on my local PC, but when I try to run on HPC systems I begin running into peculiar issues. Occasionally one of the subprocess calls seems to simply hang (e.g. on a forward/adjoint solve). I was curious if you'd experienced anything similar at any point.

Regards,

Gian

**Comment by rmodrak** [comment]
On Mon, Jul 18, 2016 at 3:19 PM, Ryan Modrak <rmodrak@princeton.edu> wrote:

    The only similar issue I've heard about is that on some LSF and PBS clusters, the workflow hangs after a long time or a large number of iterations.  I'm not aware of any cases where a subprocess call is specifically to blame.  Perhaps it is worth asking the cluster admins if they've experienced anything similar.  If it happens often enough to be disruptive, there may be some way of detecting when a subprocess stalls (link below might relevant) and then rerunning the stalled process (or rerunning all processes, if that makes things simpler).

    http://stackoverflow.com/questions/1191374/using-module-subprocess-with-timeout

**Comment by rmodrak** [comment]
On Mon, Aug 29, 2016 at 11:52 AM, Gian Matharu <gian@ualberta.ca> wrote:

From what I remember, certain sections seemed to hang. I have a feeling it was somehow related to issues with IO. It's possible that there could have been some hidden race condition but I couldn't find it and the subprocess.call command is supposed to be a blocking call.

I think the system class itself is mostly OK, but it's clearly dependent on the solver implementation. Employing parallel shots via a subprocess MPI call to a python wrapper does obfuscate things though. So a simpler solution might be preferable.

**Comment by rmodrak** [comment]
On Mon, Aug 29, 2016 12:11 PM Ryan Modrak wrote:

I agree, employing parallel shots via a subprocess MPI call to a python wrapper is quite obfuscated. Why isn't there some simple readily available solution?  Since the shots themselves are embarrasingly parallel, as a basic principle, race conditions shouldnt be an issue, right?  I don't see why not there isn't some readily available dsh script that does the trick.  For PBS clusters there is pbsdsh but that utility itself seems very halfhearted and unstable.  Please let me know if I am missing anything.

**Comment by rmodrak** [comment]
On Mon, Aug 29, 2016 at 12:28 PM, Gian Matharu <gian@ualberta.ca> wrote:

Race condition might be the wrong term in this case. It seemed to be a lack of synchronization between the processes, possibly related to reading/writing.

I ran into issues with pbsdsh which is why I left it originally. I briefly looked into a utility called gnu parallel. It basically launches serial programs in an embarrassingly parallel approach. I think the issue I had with it was finding a unique identifier (something like my_rank) to distinguish the shots.

**Comment by dkzhangchao** [comment]
Hi Ryan,

1) on our pbs cluster, firstly i load these module automatically when i log in 
module load intel/14.0.1
module load gcc/5.2.0
module load openmpi/1.4.4-intel-v12.1
module load python/2.7.5
Actually, if i print the command: python -c "import mpi4py", it can work. When the coding is running, there is also no error information about mpi4py, so it should be loaded well
 
2) Anyway, i also tried the system='pbs_torque_sm',  there is a bug about import 

Traceback (most recent call last):
  File "/scratch/l/liuqy/zhang18/Research/packages/seisflows/seisflows/system/wrappers/run_pbsdsh", line 15, in <module>
from seisflows.tools.code import loadjson, loadobj
ImportError    : from seisflows.tools.code import loadjson, loadobj

Actually, this problem also occur when i used system='pbs_sm', if i just load modules( module intel/14.0.1,gcc/5.2.0,1.4.4-intel-v12.1, python/2.7.5) at the submit node, it will meet the problem like above issue; If module are loaded automatically when i log in every time, it will not
meet this problem. So i use my .bashrc to load these module automatically, but even though, this problem occur again for the system='pbs_torque_sm'

**Comment by dkzhangchao** [comment]
when i log in every time, these module will be load. I tried 
python -c "from seisflows.tools.code import loadjson, loadobj", it can work

<img width="896" alt="qq20160923-0 2x" src="https://cloud.githubusercontent.com/assets/8068058/18798287/bfd6fa9c-819f-11e6-962d-eb1edc97cff1.png">
