### ISSUE TITLE
salvus integration?

### ISSUE THREAD

**Issue by rmodrak** [adjtomo/seisflows#59]
Has anyone tried SALVUS?  I'm hopeful this promising new solver can be made to work with SeisFlows, but still not familiar enough to say whether that would be easy or hard.  Hoping that SALVUS might eventually provide a solver alternative, at least for 2D inversions.

**Comment by gianmatharu** [comment]
I've been meaning to look into it. Last time I check the adjoint
calculations hadn't been completed, but it looks as though they are now.
Once I get a better handle on it, I'll have something to add.

**Comment by rmodrak** [comment]
From speaking with Michael Afanasiev, it sounds like salvus will employ a graph theory description of the workflow.  My sense is that the graph theory approach provides performance and scalability advantages and at the expense of flexibility and usability, while the "superscripting" in seisflows is exactly opposite.  So possibly there will be some separation in terms of what each package is best for.

Currently, the savlus workflow and nonlinear optimization routines are not open source.  Once they become so, we can get a much better sense of things.  

On the other hand, salvus solver routines have been available for a while, so it is possible now to start looking into solver integration.
